//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.SqlServer.AdventureWorksService
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTerritorySalesDrilldown
    {
        public long ID { get; set; }
        public string TerritoryName { get; set; }
        public int SalesPersonID { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
        public string SalesOrderNumber { get; set; }
        public decimal Total { get; set; }
    }
}
